# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amy's Blog
email: amykw105@gmail.com
description: This is a personal blog of web development things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amywestlake.co.uk" # the base hostname & protocol for your site
twitter_username: amykwestlake
github_username:  mimpski

# Build settings
markdown: kramdown
